добавляет шаблон катрочки фильма
dmitriydegtyarev/filmoteka pull request #1
Opened 2021-06-06 19:23 UTC by NataliiaChernieva

2021-06-06 20:20 UTC, dmitriydegtyarev requested changes
Необходимо сделать правки и сделать commit.

2021-06-06 20:20 UTC, dmitriydegtyarev commented on src/templates/film-card.hbs
> +            <div class="properties">
Лучше заменить на UL (более симантично выйдет)

2021-06-06 20:20 UTC, dmitriydegtyarev commented on src/templates/film-card.hbs
> +                <p>Vote / Votes</p>
делаем элементом списка li с классом properties-item

2021-06-06 20:20 UTC, dmitriydegtyarev commented on src/templates/film-card.hbs
> +                <p>Popularity</p>
делаем элементом списка li с классом properties-item

2021-06-06 20:20 UTC, dmitriydegtyarev commented on src/templates/film-card.hbs
> +                <p>Original Title</p>
делаем элементом списка li с классом properties-item

2021-06-06 20:20 UTC, dmitriydegtyarev commented on src/templates/film-card.hbs
> +                <p>Genre</p>
делаем элементом списка li с классом properties-item

2021-06-06 20:20 UTC, dmitriydegtyarev commented on src/templates/film-card.hbs
> +            </div>
сдесь будет закрывающийся UL

2021-06-06 20:20 UTC, dmitriydegtyarev commented on src/templates/film-card.hbs
> +            <div class="property-value">
для семантики лучше заменить на UL и класс подправить на properties-value (по аналогии как у тебя див с класом properties для первой колонки).

2021-06-06 20:20 UTC, dmitriydegtyarev commented on src/templates/film-card.hbs
> +            </div>
сдесь будет закрывающийся ul

2021-06-06 20:20 UTC, dmitriydegtyarev commented on src/templates/film-card.hbs
> +                <p>{{vote_average}} / {{vote_count}}</p>
делаем элементом списка li с классом properties-value__item

2021-06-06 20:20 UTC, dmitriydegtyarev commented on src/templates/film-card.hbs
> +                <p>{{popularity}}</p>
делаем элементом списка li с классом properties-value__item

2021-06-06 20:20 UTC, dmitriydegtyarev commented on src/templates/film-card.hbs
> +                <p class="film-origin-title">{{original_title}}</p>
делаем элементом списка li с классом properties-value__item, но твой класс film-origin__title (нас так заставляли прописывать, если есть третье слово в классе) также пусть остается для дополнительной стилизации.

2021-06-06 20:20 UTC, dmitriydegtyarev commented on src/templates/film-card.hbs
> +                <p>{{genres}}</p>
делаем элементом списка li с классом properties-value__item

2021-06-06 20:20 UTC, dmitriydegtyarev commented on src/templates/film-card.hbs
> +        <div class="buttons">
если див можно заменить на ul - лучше заменить

2021-06-06 20:20 UTC, dmitriydegtyarev commented on src/templates/film-card.hbs
> +            <button class="add-watched_button" type="button">add to Watched</button>
батон поместить внутрь элемента li

2021-06-06 20:20 UTC, dmitriydegtyarev commented on src/templates/film-card.hbs
> +            <button class="add-queue_button" type="button">add to queue</button>
батон поместить внутрь элемента li

2021-06-06 20:20 UTC, dmitriydegtyarev commented on src/templates/film-card.hbs
> +        </div>
сдесь тогда будет закрывающийся ul

2021-06-06 20:20 UTC, dmitriydegtyarev commented on src/templates/film-card.hbs
> +    <img class="film-img" src="" alt="">
сдесь пустой src

2021-06-07 18:57 UTC, NataliiaChernieva commented on src/templates/film-card.hbs
> +            <button class="add-watched_button" type="button">add to Watched</button>
не подойдет. в li должен быть однотипный контент. и будет проблема со стилями. меняю только div на ul с li.

2021-06-07 19:36 UTC, dmitriydegtyarev approved these changes

2021-06-07 19:36 UTC, merged